---
gitconfig_name:
gitconfig_email:
downloads: ~/.ansible/tmp/
code_directory: ~/repos
ansible_become_password: '{{ become_pass }}'
installed_packages:
  - fish
  - btop
  - unzip
  - curl
  - wget 
  - neovim
