---
local_username: luser
ssh_private_key_file: ~/.ssh/id_ed25519

gitconfig_name:
gitconfig_email:

downloads: ~/.ansible/tmp/

code_directory: ~/repos

installed_packages:
  - fish
  - btop
  - curl
  - wget 
  - ncdu
  - unzip
  - neovim

alpine_groups:
  - wheel
  - audio
  - input
  - video
  - netdev
