---
# gitconfig
# gitconfig_name: YOUR_USERNAME
# gitconfig_email: YOUR@EMAIL_ADDRESS

# directories
downloads: ~/.ansible/tmp/
code_directory: ~/repos

# packages
packages_installed:
  - fish
  - btop
  - curl
  - wget 
  - ncdu
  - pigz
  - unzip
  - clang
  - neovim
  - fontconfig

packages_installed_alpine:
  - gzip
  - libdeflate-utils

packages_installed_archlinux:
  - zlib-ng-compat

packages_installed_debian:

packages_installed_fedora:
