---
ssh_private_key_file: ~/.ssh/id_ed25519

gitconfig_name: philcryer
gitconfig_email: phil@philcryer.com

downloads: ~/.ansible/tmp/

code_directory: ~/repos

installed_packages:
  - fish
  - btop
  - curl
  - wget 
  - ncdu
  - unzip
  - clang
  - neovim

alpine_groups:
  - wheel
  - audio
  - input
  - video
  - netdev
