---
# gitconfig
gitconfig_name: philcryer
gitconfig_email: phil@philcryer.com

# directories
downloads: ~/.ansible/tmp/
code_directory: ~/repos

# packages
installed_packages:
  - gzip
  - fish
  - btop
  - curl
  - wget 
  - ncdu
  - unzip
  - clang
  - neovim
  - fontconfig
  - libdeflate-utils

# users' groups
alpine_groups:
  - wheel
  - audio
  - input
  - video
  - netdev

# starship
#starship_install_directory: $HOME/.local/bin
#starship_owner: '{{ user_id }}'
#starship_group: '{{ user_id }}'
