---
#downloads: ~/.ansible-downloads/
downloads: ~/.ansible/tmp/

#configure_dotfiles: yes
configure_dotfiles: no
configure_terminal: yes
configure_osx: no
#configure_osx: yes

#dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
#dotfiles_repo_accept_hostkey: yes
#dotfiles_repo_local_destination: ~/devel

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - gettext
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - readline
  - pv
  - jq
  - wget
  - tmux
  - tree
  - watch
  - hugo
  - nginx
  - htop
  - netcat
  - awscli
  #- doxygen
  #- git
  #- ssh-copy-id
  #- openssl
  #- wrk
  # new 01172019
  #- kubernetes-cli
  #- ctop
  #- docker-clean 
  #- coreutils 
  #- openssh
  #- speedtest-cli

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - caskroom/fonts
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - font-hack-nerd-font
  - vlc 
  - visual-studio-code
  #- chromedriver
  #- docker
  #  - dropbox
  #- firefox
  #- google-chrome
  #- handbrake
  #- licecap
  # - limechat
  # - macvim
  # - sequel-pro
  # - skitch
  #- slack
  #  - sublime-text
  #  - transmit
  #- torbrowser # integrated tor/firefox broswer
  #- transmission # bittorrent
  #- tunnelblick # VPN
  #- vagrant # | https://www.vagrantup.com/downloads.html
  #- vagrant-manager # 
  #- virtualbox # | https://www.virtualbox.org/

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
