---
#### packages - Linux Generic
packages_installed:
  - fish
  - btop
  - curl
  - wget
  - ncdu
  - tree
  - pigz
  - unzip
  - clang
  - neovim
  - clipman
  - luarocks
  - starship
  - xarchiver
  - fontconfig

