---
- name: Install gitconfig template
  ansible.builtin.template:
    src: templates/gitconfig.j2
    dest: '$HOME/.gitconfig'
    owner: '{{ user_id }}'
    group: '{{ user_id }}'
    mode: '0755'

- name: Install profile configuration
  ansible.builtin.copy:
    src: ../files/profile
    dest: '$HOME/.profile'
    owner: '{{ user_id }}'
    group: '{{ user_id }}'
    mode: '0755'

- name: Install fish aliases
  ansible.builtin.copy:
    src: '{{ item }}' 
    dest: '$HOME/.config/fish/functions'
    owner: '{{ user_id }}'
    group: '{{ user_id }}'
    mode: '0755'
  with_fileglob: "../files/fish_functions/*"
