all:
  hosts:
    localhost:
      user_id: fak3r
      ansible_conection: local
#      ansible_become_method: sudo
#      become: true
#      become_user: fak3r

    # web1.example.com:
    # web2.example.com:
    # db1.example.com:
    # hector.lowf.at:
    #   ansible_port: 6666
    #   become_user: linuxuser
#    calvin:
#      ansible_port: 22
#      user_id: luser
#      ansible_conection: ssh
#      ansible_become_method: doas
  #    ansible_become_password: '{{ become_password }}'
  # children:
  #   webservers:
  #     hosts:
  #       web1.example.com:
  #       web2.example.com:
  #   dbservers:
  #     hosts:
  #       db1.example.com:
  #       db2.example.com:
  #         ansible_port: 2222
  #   production:
  #     children:
  #       webservers:
  #       dbservers:
